Traceback (most recent call last):
  File "/share/home/bjiangch/group-zyl/.conda/envs/PyTorch-1.10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/home/bjiangch/group-zyl/.conda/envs/PyTorch-1.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/group/zyl/reann/2021_10_19/reann/__main__.py", line 1, in <module>
    import run.train
  File "/group/zyl/reann/2021_10_19/reann/run/train.py", line 3, in <module>
    from src.read import *
  File "/group/zyl/reann/2021_10_19/reann/src/read.py", line 133, in <module>
    Read_data(floderlist,1,start_table=start_table)
  File "/group/zyl/reann/2021_10_19/reann/src/read_data.py", line 51, in Read_data
    tmp=list(map(float,m[1:]))
ValueError: could not convert string to float: "Dipole='-0.7087900042533875"
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 172120) of binary: /share/home/bjiangch/group-zyl/.conda/envs/PyTorch-1.10/bin/python3
Traceback (most recent call last):
  File "/share/home/bjiangch/group-zyl/.conda/envs/PyTorch-1.10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/home/bjiangch/group-zyl/.conda/envs/PyTorch-1.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/share/home/bjiangch/group-zyl/.conda/envs/PyTorch-1.10/lib/python3.9/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/share/home/bjiangch/group-zyl/.conda/envs/PyTorch-1.10/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/share/home/bjiangch/group-zyl/.conda/envs/PyTorch-1.10/lib/python3.9/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/share/home/bjiangch/group-zyl/.conda/envs/PyTorch-1.10/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/share/home/bjiangch/group-zyl/.conda/envs/PyTorch-1.10/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/share/home/bjiangch/group-zyl/.conda/envs/PyTorch-1.10/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/group/zyl/reann/2021_10_19/reann/ FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2021-11-17_09:12:39
  host      : gpu1
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 172120)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
